name: Trigger Nuxt Build in VPS Container

on:
  workflow_dispatch:

jobs:
  build_on_vps:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and Build in Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ensure known_hosts on VPS already trusts GitHub
            ssh-keyscan github.com >> /root/.ssh/known_hosts

            # Build Docker image
            cd /home/${{ secrets.VPS_USER }}/frontend-builder/nuxt-builder
            docker build -t nuxt-builder .

            # Run container with SSH keys mounted read-only
            docker run --rm \
            -v /root/.ssh:/root/.ssh:ro \
            -v /home/${{ secrets.VPS_USER }}/frontend-builder/frontend-output:/output \
            nuxt-builder bash -c "
              git clone git@github.com:GuidaGG/nuxt-basic.git /app/nuxt-basic && \
              cd /app/nuxt-basic && \
              npm ci && \
              npm run generate && \
              cp -r .output/public/* /output/
            "